# Generated by Django 4.2.6 on 2024-01-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
