# Generated by Django 4.2.6 on 2024-01-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversionimage',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productversion'),
        ),
    ]
