# Generated by Django 4.2.6 on 2024-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_tags_product_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='color',
        ),
        migrations.DeleteModel(
            name='Designer',
        ),
        migrations.AddField(
            model_name='productversion',
            name='color',
            field=models.ManyToManyField(blank=True, to='product.color'),
        ),
    ]
