# Generated by Django 4.2.6 on 2024-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productversion_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
