# Generated by Django 4.2.6 on 2024-02-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_brand_slug_remove_productcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
