# Generated by Django 4.2.6 on 2024-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_shoppingcart_user_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='product.producttag'),
        ),
    ]
