# Generated by Django 4.2.6 on 2024-01-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
    ]
