# Generated by Django 4.2.6 on 2024-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address_id",
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="company_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
