# Generated by Django 4.2.6 on 2024-02-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_order_shipping_address_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_version_id",
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="cart_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checkout.shoppingcart",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
